---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-application-connectivity-validator
  namespace: kyma-system
  labels:
    app: central-application-connectivity-validator
    release: application-connector
    app.kubernetes.io/name: central-application-connectivity-validator
    app.kubernetes.io/managed-by: application-connector-manager
    app.kubernetes.io/instance: application-connector
    app.kubernetes.io/part-of: application-connector-manager
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: central-application-connectivity-validator
      release: application-connector
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: central-application-connectivity-validator
        app.kubernetes.io/part-of: application-connector-manager
        release: application-connector
    spec:
      serviceAccountName: central-application-connectivity-validator
      containers:
      - name: central-application-connectivity-validator
        image: europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:v20230818-6f20d4ee
        imagePullPolicy: IfNotPresent
        args:
          - "/app/centralapplicationconnectivityvalidator"
          - "--proxyPort=8080"
          - "--externalAPIPort=8081"
          - "--eventingPathPrefixV1=/%%APP_NAME%%/v1/events"
          - "--eventingPathPrefixV2=/%%APP_NAME%%/v2/events"
          - "--eventingPublisherHost=eventing-event-publisher-proxy.kyma-system"
          - "--eventingDestinationPath=/publish"
          - "--eventingPathPrefixEvents=/%%APP_NAME%%/events"
          - "--appNamePlaceholder=%%APP_NAME%%"
        env:
          - name: APP_LOG_FORMAT
            value: "json"
          - name: APP_LOG_LEVEL
            value: "warn"
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: http-proxy
          - containerPort: 8081
            name: http-api-port
        securityContext:
          runAsUser: 1000
          privileged: false
          allowPrivilegeEscalation: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-application-gateway
  namespace: kyma-system
  labels:
    app: central-application-gateway
    release: application-connector
    app.kubernetes.io/name: central-application-gateway
    app.kubernetes.io/managed-by: application-connector-manager
    app.kubernetes.io/instance: application-connector
    app.kubernetes.io/part-of: application-connector-manager
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: central-application-gateway
      release: application-connector
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: central-application-gateway
        app.kubernetes.io/part-of: application-connector-manager
        release: application-connector
    spec:
      serviceAccountName: central-application-gateway
      containers:
      - name: central-application-gateway
        image: europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:v20230821-f9ec5ecd
        imagePullPolicy: IfNotPresent
        args:
          - "/app/applicationgateway"
          - "--proxyPort=8080"
          - "--proxyPortCompass=8082"
          - "--externalAPIPort=8081"
          - "--applicationSecretsNamespace=kyma-system"
          - "--requestTimeout=10"
          - "--proxyTimeout=10"
          - "--proxyCacheTTL=120"
          - "--requestLogging=false"
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 64Mi
        ports:
          - containerPort: 8080
            name: http-proxy
          - containerPort: 8082
            name: http-proxy-mps
          - containerPort: 8081
            name: http-api-port
        securityContext:
          runAsUser: 1000
          privileged: false
          allowPrivilegeEscalation: false
---
# Source: application-connector/charts/central-application-connectivity-validator/templates/autoscaling.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: central-application-connectivity-validator
  namespace: kyma-system
  labels:
    app: central-application-connectivity-validator
    release: application-connector
    app.kubernetes.io/name: central-application-connectivity-validator
    app.kubernetes.io/managed-by: application-connector-manager
    app.kubernetes.io/instance: application-connector
    app.kubernetes.io/part-of: application-connector-manager
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: central-application-connectivity-validator
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
# Source: application-connector/charts/central-application-gateway/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: central-application-gateway
  namespace: kyma-system
  labels:
    app: central-application-gateway
    release: application-connector
    app.kubernetes.io/name: central-application-gateway
    app.kubernetes.io/managed-by: application-connector-manager
    app.kubernetes.io/instance: application-connector
    app.kubernetes.io/part-of: application-connector-manager
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: central-application-gateway
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
