module-name: application-connector-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:v20231218-d6717ba0
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"