module-name: application-connector-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:v20231124-a0ea0afb
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"