module-name: application-connector-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:v20240212-3818afbd
  - europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:v20231214-12badce5
  - europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:v20240212-f2ca576c
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"