module-name: application-connector-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:1.1.7
  - europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:v20240910-57c6730a
  - europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:v20240910-57c6730a
  - europe-docker.pkg.dev/kyma-project/prod/compass-runtime-agent:v20240910-57c6730a
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
