module-name: application-connector-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:v20231024-4d88a4d5
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"