---
# Source: application-connector/templates/limit-range.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: kyma-default
  namespace: kyma-system
  labels:
    release: applicationconnector-sample
    helm.sh/chart: application-connector-1.0.0
    app.kubernetes.io/name: application-connector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
spec:
  limits:
  - max:
      memory: 1024Mi # Maximum memory that a container can request
    default:
      # If a container does not specify memory limit, this default value will be applied.
      # If a container tries to allocate more memory, container will be OOM killed.
      memory: 96Mi
    defaultRequest:
      # If a container does not specify memory request, this default value will be applied.
      # The scheduler considers this value when scheduling a container to a node.
      # If a node has not enough memory, such pod will not be created.
      memory: 32Mi
    type: Container
---
# Source: application-connector/charts/central-application-gateway/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: central-application-gateway
  namespace: kyma-system
  labels:
    app: central-application-gateway
    release: applicationconnector-sample
    helm.sh/chart: central-application-gateway-0.1.0
    app.kubernetes.io/name: central-application-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
---
# Source: application-connector/templates/helm-secret.yaml
apiVersion: v1
data:
  tls.crt: "VEJE"
  tls.key: "VEJE"
kind: Secret
metadata:
  name: helm-secret
  namespace: kyma-system
  labels:
    release: applicationconnector-sample
    helm.sh/chart: application-connector-1.0.0
    app.kubernetes.io/name: application-connector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
type: Opaque
---
# Source: application-connector/charts/central-application-gateway/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: central-application-gateway-role
  labels:
    app: central-application-gateway
    release: applicationconnector-sample
    helm.sh/chart: central-application-gateway-0.1.0
    app.kubernetes.io/name: central-application-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
rules:
- apiGroups: ["applicationconnector.kyma-project.io"]
  resources: ["applications"]
  verbs: ["get"]
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["get"]
---
# Source: application-connector/templates/cluster-role-binding.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: applicationconnector-sample-application-connector
  labels:
    app: applicationconnector-sample
    release: applicationconnector-sample
    helm.sh/chart: application-connector-1.0.0
    app.kubernetes.io/name: application-connector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
rules:
- apiGroups: ["applicationconnector.kyma-project.io"]
  resources: ["applications"]
  verbs: ["get", "list", "update","create", "delete", "watch"]
---
# Source: application-connector/charts/central-application-gateway/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: central-application-gateway-rolebinding
  labels:
    app: central-application-gateway
    release: applicationconnector-sample
    helm.sh/chart: central-application-gateway-0.1.0
    app.kubernetes.io/name: central-application-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
subjects:
- kind: User
  name: system:serviceaccount:kyma-system:central-application-gateway
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: central-application-gateway-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: application-connector/templates/cluster-role-binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: applicationconnector-sample-application-connector
  labels:
    app: applicationconnector-sample
    release: applicationconnector-sample
    helm.sh/chart: application-connector-1.0.0
    app.kubernetes.io/name: application-connector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
subjects:
- kind: User
  name: system:serviceaccount:kyma-system:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: applicationconnector-sample-application-connector
---
# Source: application-connector/charts/central-application-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: central-application-gateway
  namespace: kyma-system
  labels:
    application: central-application-gateway
    app: central-application-gateway
    release: applicationconnector-sample
    helm.sh/chart: central-application-gateway-0.1.0
    app.kubernetes.io/name: central-application-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      name: http-api-port
    - port: 8080
      protocol: TCP
      name: http-proxy
    - port: 8082
      protocol: TCP
      name: http-proxy-mps
  selector:
    app: central-application-gateway
    release: applicationconnector-sample
---
# Source: application-connector/charts/central-application-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-application-gateway
  namespace: kyma-system
  labels:
    app: central-application-gateway
    release: applicationconnector-sample
    helm.sh/chart: central-application-gateway-0.1.0
    app.kubernetes.io/name: central-application-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: central-application-gateway
      release: applicationconnector-sample
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: central-application-gateway
        release: applicationconnector-sample
    spec:
      serviceAccountName: central-application-gateway
      containers:
      - name: central-application-gateway
        image: eu.gcr.io/kyma-project/central-application-gateway:v20221014-ec1ce988
        imagePullPolicy: IfNotPresent
        args:
          - "/app/applicationgateway"
          - "--proxyPort=8080"
          - "--proxyPortCompass=8082"
          - "--externalAPIPort=8081"
          - "--applicationSecretsNamespace=kyma-system"
          - "--requestTimeout=10"
          - "--proxyTimeout=10"
          - "--proxyCacheTTL=120"
          - "--requestLogging=false"
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 64Mi
        ports:
          - containerPort: 8080
            name: http-proxy
          - containerPort: 8082
            name: http-proxy-mps
          - containerPort: 8081
            name: http-api-port
        securityContext:
          runAsUser: 1000
          privileged: false
          allowPrivilegeEscalation: false
---
# Source: application-connector/charts/central-application-gateway/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: central-application-gateway
  namespace: kyma-system
  labels:
    app: central-application-gateway
    release: applicationconnector-sample
    helm.sh/chart: central-application-gateway-0.1.0
    app.kubernetes.io/name: central-application-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: applicationconnector-sample
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: central-application-gateway
  targetCPUUtilizationPercentage: 80
