# permissions for end users to view applicationconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: applicationconnector-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: application-connector-manager
    app.kubernetes.io/part-of: application-connector-manager
    app.kubernetes.io/managed-by: kustomize
  name: applicationconnector-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - applicationconnectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - applicationconnectors/status
  verbs:
  - get
