apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    reconciler.kyma-project.io/managed-by: reconciler
    reconciler.kyma-project.io/origin-version: main
  name: applications.applicationconnector.kyma-project.io
spec:
  conversion:
    strategy: None
  group: applicationconnector.kyma-project.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    shortNames:
    - app
    singular: application
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              accessLabel:
                maxLength: 63
                pattern: ^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$
                type: string
              compassMetadata:
                properties:
                  applicationId:
                    type: string
                  authentication:
                    properties:
                      clientIds:
                        items:
                          type: string
                        type: array
                    required:
                    - clientIds
                    type: object
                required:
                - authentication
                type: object
              description:
                type: string
              displayName:
                type: string
              group:
                type: string
              labels:
                additionalProperties:
                  type: string
                nullable: true
                type: object
              longDescription:
                type: string
              providerDisplayName:
                type: string
              services:
                items:
                  properties:
                    authCreateParameterSchema:
                      description: New fields used by V2 version
                      type: string
                    description:
                      type: string
                    displayName:
                      type: string
                    entries:
                      items:
                        properties:
                          accessLabel:
                            maxLength: 63
                            pattern: ^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$
                            type: string
                          apiType:
                            type: string
                          centralGatewayUrl:
                            type: string
                          credentials:
                            properties:
                              authenticationUrl:
                                type: string
                              csrfInfo:
                                properties:
                                  tokenEndpointURL:
                                    type: string
                                required:
                                - tokenEndpointURL
                                type: object
                              secretName:
                                type: string
                              type:
                                type: string
                            required:
                            - type
                            - secretName
                            type: object
                          gatewayUrl:
                            type: string
                          id:
                            type: string
                          name:
                            description: New fields used by V2 version
                            type: string
                          requestParametersSecretName:
                            type: string
                          specificationUrl:
                            type: string
                          targetUrl:
                            type: string
                          type:
                            enum:
                            - API
                            - Events
                            type: string
                        required:
                        - type
                        type: object
                      type: array
                    id:
                      type: string
                    identifier:
                      type: string
                    labels:
                      additionalProperties:
                        type: string
                      description: Deprecated
                      nullable: true
                      type: object
                    longDescription:
                      type: string
                    name:
                      type: string
                    providerDisplayName:
                      type: string
                    tags:
                      items:
                        type: string
                      type: array
                  required:
                  - id
                  - name
                  - displayName
                  - providerDisplayName
                  - description
                  - entries
                  type: object
                type: array
              skipInstallation:
                type: boolean
              skipVerify:
                type: boolean
              tags:
                description: New fields used by V2 version
                items:
                  type: string
                nullable: true
                type: array
              tenant:
                type: string
            type: object
          status:
            properties:
              installationStatus:
                description: Represents the status of Application release installation
                properties:
                  description:
                    type: string
                  status:
                    type: string
                required:
                - status
                type: object
            required:
            - installationStatus
            type: object
        type: object
    served: true
    storage: true
