name: CRA Build

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-cra.yaml"
      - "components/compass-runtime-agent"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/build-cra.yaml"
      - "components/compass-runtime-agent"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: compass-runtime-agent
      dockerfile: components/compass-runtime-agent/Dockerfile
      context: components/compass-runtime-agent
      export-tags: true
