name: ACM Build

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yaml"
      - "main.go"
      - "api/**"
      - "pkg/**"
      - "controllers/**"
      - "application-connector.yaml"
      - "application-connector-dependencies.yaml"
      - "go.sum"
      - "go.mod"
      - "Dockerfile"
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/build.yaml"
      - "main.go"
      - "api/**"
      - "pkg/**"
      - "controllers/**"
      - "application-connector.yaml"
      - "application-connector-dependencies.yaml"
      - "go.sum"
      - "go.mod"
      - "Dockerfile"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: application-connector-manager
      dockerfile: Dockerfile
      context: .
      export-tags: true
