name: compass-runtime-agent
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: components/compass-runtime-agent/go.mod
        cache-dependency-path: components/compass-runtime-agent/go.sum
    - name: Run unit tests
      working-directory: ./components/compass-runtime-agent
      run: make test

  k3d-integration:
    # we're using reusable because we can't modify workflows as contributors
    # it could cause the secret leakeages
    uses: "./.github/workflows/reusable-k3d-agent-test.yml"
    with:
      k3d-version: v5.6.0
    secrets:
      compass-host: ${{ secrets.COMPASS_HOST }}
      compass-client-id: ${{ secrets.COMPASS_CLIENT_ID }}
      compass-client-secret: ${{ secrets.COMPASS_CLIENT_SECRET }}
