name: documentation
run-name: ${{github.event.pull_request.title}}
on: [ pull_request ]
jobs:
  markdown-link-check: #please update https://github.com/kyma-project/test-infra/blob/main/prow/config.yaml if this name is changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'  
          use-verbose-mode: 'yes'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
          check-modified-files-only: 'yes'
          base-branch: '${{ github.base_ref }}'